task: 'widar3G6_Units'
init_rand_seed: 41
tqdm_disable: True
tensorboard_folder: 'runs/widar3G6/'        
trained_model_folder: 'weights/widar3G6/'
model_save_enable: False
log_folder: 'logs/widar3G6/'
log_enable: True       

num_epochs: 55
early_stop: 15 # the number of epochs to stop the training if the validation loss does not decrease
batch_size: 32
num_workers: 16
optimizer: 'AdamW' # 'AdamW', 'Lion' (https://github.com/lucidrains/lion-pytorch)
lr: 0.001    # adamW: 0.001, Lion: 0.0004 (3-10x smaller than that for AdamW)
weight_decay: 0.004 # adamW: 0.004, Lion: 0.01  (Lion is 3-10x larger than that for AdamW)
max_norm: None # the maximum norm for the gradient clipping
criterion: 'label_smoothing' # 'cross_entropy', 'mse', label_smoothing
resume_training: False # OR put the weirf_crate_smalghts name for resume training: 'name_of_the_weights.pth'
metric: 'accuracy' # 'accuracy', 'f1_score', 'precision', 'recall', 'mpjpe_2d', 'mpjpe_3d'

model_name: 'units_standard'
model_input_shape: 'BLC'  # BCHW, BLC, BTCHW, B2CNFT # B: batch size, C: channel, H: height, W: width, T: time length, N: number of (WiFi CSI) links, F: frequency bins
num_classes: 6 # the number of classes in the dataset
in_channels: 180 # the number of input channels == 'C' in the model_input_shape

dataset_name: 'widar3'
dataset_path: 'Open_Datasets/widar3'
preload: False
preprocess: True
concat_rx: False
z_score: False
format: 'polar' # 'polar', 'cartesian', 'complex', 'dfs'
time_length: 2560 # the length of the time series data.
data_split: [] # get the train, validattion, and test sets from the all_dataset ; 
                           # If data_split is [], we get the train and validation sets from the train_dataset with ratio 0.8, 0.2, respectively. the test set is from the test_dataset

# all_dataset:
#   user_list: [1,2,3,4,5,6,7,8,9,10,11]   # the selected user list
#   gesture_list: [0,6]       # the selected gesture from the SORTED_GES_LIST in tha widar3.py dataset file
#   ges_from_same_folder: False  
#   room_list: [1,3]     # the selected room list: 1, 2, 3
#   select_rx: [1] # [1,2,3,4,5,6]

# following the RFboost setup
train_dataset:
  user_list: [3,7,8,9]   # the selected user list
  gesture_list: [0,6]       # the selected gesture from the SORTED_GES_LIST in tha widar3.py dataset file
  ges_from_same_folder: True  
  room_list: [3]     # the selected room list: 1, 2, 3
  select_rx: [1,2,3,4,5,6]

test_dataset:
  user_list: [1,5,6,10,11,12,13,14,15,16]  # the selected user list
  gesture_list: [0,6]       #[start_index, end_index] the selected gesture from the SORTED_GES_LIST in tha widar3.py dataset file
  ges_from_same_folder: True  
  room_list: [1,2]     # the selected room list: 1, 2, 3
  select_rx: [1,2,3,4,5,6] # [1,2,3,4,5,6]