task: 'HuPR_resnet18'
init_rand_seed: 41
tqdm_disable: True
tensorboard_folder: 'runs/HuPR/'        
trained_model_folder: 'weights/HuPR/'
model_save_enable: False
log_folder: 'logs/HuPR/'    
log_enable: True   

num_epochs: 100
early_stop: 20 # the number of epochs to stop the training if the validation loss does not decrease
batch_size: 16
num_workers: 32
optimizer: 'AdamW' # 'AdamW', 'Lion' (https://github.com/lucidrains/lion-pytorch)
lr: 0.001    # adamW: 0.001, Lion: 0.0004 (3-10x smaller than that for AdamW)
weight_decay: 0.004 # adamW: 0.004, Lion: 0.01  (Lion is 3-10x larger than that for AdamW)
max_norm: None
criterion: 'bone_loss' # 'cross_entropy', 'mse', label_smoothing
resume_training: False # OR put the weights name for resume training: 'name_of_the_weights.pth'
metric: 'mpjpe_2d' # 'accuracy', 'f1_score', 'precision', 'recall', 'mpjpe_2d', 'mpjpe_3d'

# resnet18, resnet34, resnet50, resnet101, resnet152, 
# densenet121, densenet161, densenet169, densenet201,
# swin_t, swin_s, swin_b, 
# swin_V2_t, swin_V2_s, swin_V2_b
model_name: 'resnet18'
model_input_shape: 'BCHW'  # BCHW, BLC, BTCHW, B2CNFT # B: batch size, C: channel, H: height, W: width, T: time length, N: number of (WiFi CSI) links, F: frequency bins
num_classes: 28 # the number of classes in the dataset
in_channels: 32 # the number of input channels

dataset_name: 'HuPR'
dataset_path: 'Open_Datasets/HuPR'
preload: True
data_split: [] # get the train, validattion, and test sets from the all_dataset ; 
                           # If data_split is [], we get the train and validation sets from the train_dataset with ratio 0.8, 0.2, respectively. the test set is from the test_dataset
format: 'polar' # 'polar', 'cartesian', 'complex', 

# all_dataset:
#   file_indexes: []  # empty means all files

train_dataset:
  file_indexes: [0, 1, 2, 3, 4, 8, 9, 10, 17, 18, 19, 21, 22, 23, 24, 28, 29, 30, 32, 33, 35, 38, 40, 41, 46, 48, 49, 55, 56, 58, 61, 62, 63, 66, 67, 68, 69, 70, 71, 72, 74, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 89, 90, 91, 93, 94, 95, 97, 98, 100, 101, 103, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 119, 120, 123, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 137, 138, 142, 143, 144, 145, 146, 148, 151, 152, 155, 156, 157, 160, 161, 168, 171, 172, 173, 174, 176, 177, 178, 181, 182, 183, 184, 187, 188, 191, 193, 194, 195, 197, 203, 206, 207, 208, 209, 210, 212, 213, 215, 221, 222, 223, 224, 227, 230, 231, 232, 233, 234]

test_dataset:
  file_indexes: [5, 6, 7, 11, 12, 13, 14, 15, 16, 20, 25, 26, 27, 31, 34, 36, 37, 39, 42, 43, 44, 45, 47, 50, 51, 52, 53, 54, 57, 59, 60, 64, 65, 73, 75, 76, 87, 88, 92, 96, 99, 102, 104, 118, 121, 122, 124, 125, 136, 139, 140, 141, 147, 149, 150, 153, 154, 158, 159, 162, 163, 164, 165, 166, 167, 169, 170, 175, 179, 180, 185, 186, 189, 190, 192, 196, 198, 199, 200, 201, 202, 204, 205, 211, 214, 216, 217, 218, 219, 220, 225, 226, 228, 229]